package yy;

import yy.layers.GMRLayer;

typedef GMRoom = {
	resourceType:String,
	resourceVersion:String,
	name:String,
	isDnd:Bool,
	volume:Float,
	parentRoom:Any,
	views:Array<{
		inherit:Bool,
		visible:Bool,
		xview:Int,
		yview:Int,
		wview:Int,
		hview:Int,
		xport:Int,
		yport:Int,
		wport:Int,
		hport:Int,
		hborder:Int,
		vborder:Int,
		hspeed:Int,
		vspeed:Int,
		objectId:Any
	}>,
	layers:Array<GMRLayer>,
	inheritLayers:Bool,
	creationCodeFile:String,
	inheritCode:Bool,
	instanceCreationOrder:Array<{
		name:String,
		path:String
	}>,
	inheritCreationOrder:Bool,
	sequenceId:Any,
	roomSettings:{
		inheritRoomSettings:Bool,
		Width:Int,
		Height:Int,
		persistent:Bool
	},
	viewSettings:{
		inheritViewSettings:Bool,
		enableViews:Bool,
		clearViewBackground:Bool,
		clearDisplayBuffer:Bool
	},
	physicsSettings:{
		inheritPhysicsSettings:Bool,
		PhysicsWorld:Bool,
		PhysicsWorldGravityX:Float,
		PhysicsWorldGravityY:Float,
		PhysicsWorldPixToMetres:Float
	},
	parent:{
		name:String,
		path:String
	}
};