package yy;

typedef GMTileSet = {
	resourceType:String,
	resourceVersion:String,
	name:String,
	spriteId:{
		name:String,
		path:String
	},
	tileWidth:Int,
	tileHeight:Int,
	tilexoff:Int,
	tileyoff:Int,
	tilehsep:Int,
	tilevsep:Int,
	out_tilehborder:Int,
	out_tilevborder:Int,
	spriteNoExport:Bool,
	textureGroupId:{
		name:String,
		path:String
	},
	out_columns:Int,
	tile_count:Int,
	autoTileSets:Array<{
		resourceType:String,
		resourceVersion:String,
		name:String,
		tiles:Array<Int>,
		closed_edge:Bool
	}>,
	tileAnimationFrames:Array<Any>,
	tileAnimationSpeed:Float,
	tileAnimation:{
		FrameData:Array<Int>,
		SerialiseFrameCount:Int
	},
	macroPageTiles:{
		SerialiseWidth:Int,
		SerialiseHeight:Int,
		TileSerialiseData:Array<Any>
	},
	parent:{
		name:String,
		path:String
	}
};